[package]
edition = "2021"
name = "keychat-relay-ext"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# grpc authorization server
[[bin]]
name = "keychat-relay-gas"
path = "src/gas.rs"

# storage authorization server
[[bin]]
name = "keychat-relay-sas"
path = "src/sas.rs"

[build-dependencies]
tonic-build = {version = "0.10", features = ["prost"]}

[dependencies]
# keychat_rust_ffi_plugin = { package = "keychat_rust_ffi_plugin", path = "../../keychat_rust_ffi_plugin/rust" }
# cdk-common = {package = "cdk-common", path = "../../cdk/crates/cdk-common"}
# cdk-sqlite = {package = "cdk-sqlite", path = "../../cdk/crates/cdk-sqlite"}
# cdk = {package = "cdk", path = "../../cdk/crates/cdk"}
# cashu = {package = "cashu", path = "../../cdk/crates/cashu"}

keychat_rust_ffi_plugin = { git = "https://github.com/keychat-io/keychat_rust_ffi_plugin.git", branch = "cdk3" }
cdk-sqlite = { git = "https://github.com/keychat-io/cdk.git", branch = "kc2", package = "cdk-sqlite" }
cdk = { git = "https://github.com/keychat-io/cdk.git", branch = "kc2", package = "cdk" }
cdk-common = { git = "https://github.com/keychat-io/cdk.git", branch = "kc2", package = "cdk-common" }
cashu = { git = "https://github.com/keychat-io/cdk.git", branch = "kc2", package = "cashu" }

prost = "0.12"
tokio-stream = {version = "0.1.14", features = ["sync"]}
tonic = "0.10"
# url = {version = "2.4.0", features = ["serde"]}
#
dashmap = "6.0.1"
parking_lot = "0.12"
axum = {version = "0.7.4", features = []}
tower-http = { version = "0.5.0", features = ["trace"] }
dotenvy.workspace = true
rust-s3.workspace = true
aws-creds.workspace = true
http.workspace = true
base64-simd.workspace = true
url.workspace = true
#
flume.workspace = true
futures.workspace = true
tokio.workspace = true
#
anyhow.workspace = true
clap.workspace = true
faster-hex.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
