# Enable pay to relay
enabled = true

# listen = "0.0.0.0:3002"
listen = "0.0.0.0:3001"

# for proxy: get ip from header
remote_ip_header = "x-forwarded-for"

allow_pending = false
allow_free = false

database = "relay.red"
timeout_ms = 3000

[fee]
unit="sat"
maxsize=104857600
mints = [
  "https://8333.space:3338",
]
# for api /v1/info
expired = "14 Days"
# untrusted_mint_balance_limit = 512
# untrusted_mint_should_transfer = 132

# cost_per_event = 1
# 10m
[[fee.prices]]
min=0
max=10485760
price=1

[[fee.prices]]
min=10485760
max=104857600
price=2

[limits.cashu_failed]
secs=600
allow=3
